version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: fire-insurance-db
    environment:
      POSTGRES_DB: fire-insurance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Faraz@123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    command: 
      - "postgres"
      - "-c"
      - "update_process_title=off"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fire-insurance"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  gateway:
    build:
      context: ../service-fire-insurance
      dockerfile: src/Gateway/Dockerfile
    container_name: fire-insurance-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=fire-insurance;Username=postgres;Password=Faraz@123;Include Error Detail=true;
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fire-insurance-network

volumes:
  postgres_data:
    name: fire-insurance-db-data

networks:
  fire-insurance-network:
    driver: bridge
