apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
    component: web
data:
  nextauth-url: "https://fireinsurance.example.com"
  api-url: "http://backend:80"
