apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: web
    spec:
      containers:
      - name: frontend
        image: frontend:latest  # Will be overridden by kustomize
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        # NextAuth configuration - will be injected from secrets
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: nextauth-url
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: nextauth-secret
        # Backend API URL
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api-url
        # Google reCAPTCHA - will be injected from secrets
        - name: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: recaptcha-site-key
        resources:
          limits:
            memory: "512Mi"
            cpu: "256m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
