apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  labels:
    app: frontend
    component: web
type: Opaque
stringData:
  # These are placeholder values - will be replaced by actual secrets from Vault in CI/CD
  nextauth-secret: "REPLACE_ME"
  recaptcha-site-key: "REPLACE_ME"
