apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      containers:
      - name: backend
        image: backend:latest  # Will be overridden by kustomize
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        # Database connection string - will be injected from secrets
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-connection-string
        # JWT configuration - will be injected from secrets
        - name: Jwt__SigningKey
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-signing-key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt-audience
        # Captcha configuration
        - name: Captcha__MinimumScore
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: captcha-minimum-score
        - name: Captcha__VerificationUrl
          value: "https://www.google.com/recaptcha/api/siteverify"
        # SMS Provider configuration - will be injected from secrets
        - name: SmsProvider__BaseUrl
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sms-provider-base-url
        - name: SmsProvider__Username
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sms-provider-username
        - name: SmsProvider__Password
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sms-provider-password
        # Saman Services configuration - will be injected from secrets
        - name: SamanServices__BaseUrl
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: saman-services-base-url
        - name: SamanServices__Key
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: saman-services-key
        # OTP configuration
        - name: Otp__ExpirationTime
          value: "00:03:00"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
