apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend
    component: api
type: Opaque
stringData:
  # These are placeholder values - will be replaced by actual secrets from Vault in CI/CD
  database-connection-string: "REPLACE_ME"
  jwt-signing-key: "REPLACE_ME"
  sms-provider-base-url: "REPLACE_ME"
  sms-provider-username: "REPLACE_ME"
  sms-provider-password: "REPLACE_ME"
  saman-services-base-url: "REPLACE_ME"
  saman-services-key: "REPLACE_ME"
