apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: backend
