apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fireinsurance-prod

resources:
  - ../../base/backend
  - ../../base/frontend
  - namespace.yaml

commonLabels:
  environment: prod

# Image tags will be set via kustomize edit in CI/CD
images:
  - name: backend
    newName: registry-3272c4a82a-fireinsurance-prod.apps.ir-central1.arvancaas.ir/backend
    newTag: latest
  - name: frontend
    newName: registry-3272c4a82a-fireinsurance-prod.apps.ir-central1.arvancaas.ir/frontend
    newTag: latest

# Patch replica counts for production
replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

# ConfigMap patches for production environment
configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - jwt-issuer=https://api.fireinsurance.example.com
      - jwt-audience=https://api.fireinsurance.example.com
  - name: frontend-config
    behavior: merge
    literals:
      - nextauth-url=https://fireinsurance.example.com
      - api-url=http://backend:80

# Production-specific resource adjustments
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 512m
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 512m
