name: Deploy to Stage

on:
  workflow_run:
    workflows: ["Build Backend", "Build Frontend"]
    types: [completed]
    branches: [main, master]
  workflow_dispatch:
    inputs:
      deploy_backend:
        description: 'Deploy backend service'
        required: true
        type: boolean
        default: true
      deploy_frontend:
        description: 'Deploy frontend service'
        required: true
        type: boolean
        default: true

permissions:
  contents: write
  id-token: write

env:
  REGISTRY: registry-3272c4a82a-fireinsurance-prod.apps.ir-central1.arvancaas.ir
  REGISTRY_USERNAME: noyanregistry
  ENVIRONMENT: stage
  NAMESPACE: fireinsurance-stage

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: stage
    # Run if:
    # 1. Manual trigger with deploy_backend=true, OR
    # 2. Build Backend workflow completed successfully
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.deploy_backend) ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.name == 'Build Backend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          url: https://noyanvault.paratechco.com
          role: github-actions
          secrets: |
            secret/data/fireinsurance/stage kubeconfig | KUBECONFIG_CONTENT ;
            secret/data/fireinsurance/stage database_connection_string | DATABASE_CONNECTION_STRING ;
            secret/data/fireinsurance/stage jwt_signing_key | JWT_SIGNING_KEY ;
            secret/data/fireinsurance/stage sms_provider_base_url | SMS_PROVIDER_BASE_URL ;
            secret/data/fireinsurance/stage sms_provider_username | SMS_PROVIDER_USERNAME ;
            secret/data/fireinsurance/stage sms_provider_password | SMS_PROVIDER_PASSWORD ;
            secret/data/fireinsurance/stage saman_services_base_url | SAMAN_SERVICES_BASE_URL ;
            secret/data/fireinsurance/stage saman_services_key | SAMAN_SERVICES_KEY ;
            secret/data/fireinsurance/stage nextauth_secret | NEXTAUTH_SECRET ;
            secret/data/fireinsurance/stage recaptcha_site_key | RECAPTCHA_SITE_KEY

      - name: Setup Kubernetes tools
        uses: ./.github/actions/setup-k8s-tools

      - name: Configure kubectl
        uses: ./.github/actions/configure-kubectl
        with:
          kubeconfig-content: ${{ env.KUBECONFIG_CONTENT }}

      - name: Update kustomization for backend
        uses: ./.github/actions/update-kustomization
        with:
          overlay-path: infra/k8s/overlays/stage
          service-name: backend
          registry: ${{ env.REGISTRY }}
          image-name: backend
          image-tag: main-${{ github.sha }}
          environment: ${{ env.ENVIRONMENT }}
          branch: ${{ github.ref_name }}

      - name: Manage backend secrets
        uses: ./.github/actions/manage-k8s-secrets
        with:
          namespace: ${{ env.NAMESPACE }}
          database-connection-string: ${{ env.DATABASE_CONNECTION_STRING }}
          jwt-signing-key: ${{ env.JWT_SIGNING_KEY }}
          sms-provider-base-url: ${{ env.SMS_PROVIDER_BASE_URL }}
          sms-provider-username: ${{ env.SMS_PROVIDER_USERNAME }}
          sms-provider-password: ${{ env.SMS_PROVIDER_PASSWORD }}
          saman-services-base-url: ${{ env.SAMAN_SERVICES_BASE_URL }}
          saman-services-key: ${{ env.SAMAN_SERVICES_KEY }}
          nextauth-secret: ${{ env.NEXTAUTH_SECRET }}
          recaptcha-site-key: ${{ env.RECAPTCHA_SITE_KEY }}

      - name: Deploy backend to Kubernetes
        uses: ./.github/actions/deploy-to-k8s
        with:
          overlay-path: infra/k8s/overlays/stage
          namespace: ${{ env.NAMESPACE }}
          deploy-backend: 'true'
          deploy-frontend: 'false'
          timeout: 5m

      - name: Deployment summary
        if: always()
        run: |
          echo "## Backend Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Namespace**: ${{ env.NAMESPACE }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Backend Image**: ${{ env.REGISTRY }}/backend:main-${{ github.sha }}" >> $GITHUB_STEP_SUMMARY

  deploy-frontend:
    runs-on: ubuntu-latest
    environment: stage
    # Run if:
    # 1. Manual trigger with deploy_frontend=true, OR
    # 2. Build Frontend workflow completed successfully
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.deploy_frontend) ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.name == 'Build Frontend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          url: https://noyanvault.paratechco.com
          role: github-actions
          secrets: |
            secret/data/fireinsurance/stage kubeconfig | KUBECONFIG_CONTENT ;
            secret/data/fireinsurance/stage database_connection_string | DATABASE_CONNECTION_STRING ;
            secret/data/fireinsurance/stage jwt_signing_key | JWT_SIGNING_KEY ;
            secret/data/fireinsurance/stage sms_provider_base_url | SMS_PROVIDER_BASE_URL ;
            secret/data/fireinsurance/stage sms_provider_username | SMS_PROVIDER_USERNAME ;
            secret/data/fireinsurance/stage sms_provider_password | SMS_PROVIDER_PASSWORD ;
            secret/data/fireinsurance/stage saman_services_base_url | SAMAN_SERVICES_BASE_URL ;
            secret/data/fireinsurance/stage saman_services_key | SAMAN_SERVICES_KEY ;
            secret/data/fireinsurance/stage nextauth_secret | NEXTAUTH_SECRET ;
            secret/data/fireinsurance/stage recaptcha_site_key | RECAPTCHA_SITE_KEY

      - name: Setup Kubernetes tools
        uses: ./.github/actions/setup-k8s-tools

      - name: Configure kubectl
        uses: ./.github/actions/configure-kubectl
        with:
          kubeconfig-content: ${{ env.KUBECONFIG_CONTENT }}

      - name: Update kustomization for frontend
        uses: ./.github/actions/update-kustomization
        with:
          overlay-path: infra/k8s/overlays/stage
          service-name: frontend
          registry: ${{ env.REGISTRY }}
          image-name: frontend
          image-tag: main-${{ github.sha }}
          environment: ${{ env.ENVIRONMENT }}
          branch: ${{ github.ref_name }}

      - name: Manage frontend secrets
        uses: ./.github/actions/manage-k8s-secrets
        with:
          namespace: ${{ env.NAMESPACE }}
          database-connection-string: ${{ env.DATABASE_CONNECTION_STRING }}
          jwt-signing-key: ${{ env.JWT_SIGNING_KEY }}
          sms-provider-base-url: ${{ env.SMS_PROVIDER_BASE_URL }}
          sms-provider-username: ${{ env.SMS_PROVIDER_USERNAME }}
          sms-provider-password: ${{ env.SMS_PROVIDER_PASSWORD }}
          saman-services-base-url: ${{ env.SAMAN_SERVICES_BASE_URL }}
          saman-services-key: ${{ env.SAMAN_SERVICES_KEY }}
          nextauth-secret: ${{ env.NEXTAUTH_SECRET }}
          recaptcha-site-key: ${{ env.RECAPTCHA_SITE_KEY }}

      - name: Deploy frontend to Kubernetes
        uses: ./.github/actions/deploy-to-k8s
        with:
          overlay-path: infra/k8s/overlays/stage
          namespace: ${{ env.NAMESPACE }}
          deploy-backend: 'false'
          deploy-frontend: 'true'
          timeout: 5m

      - name: Deployment summary
        if: always()
        run: |
          echo "## Frontend Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Namespace**: ${{ env.NAMESPACE }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend Image**: ${{ env.REGISTRY }}/frontend:main-${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
